vars:
- params.yaml


stages:
  join:
    desc: Concatenate the two datasets into one
    cmd: >
      lyscripts data join
      --inputs data/2022-isb-multisite.csv data/2022-clb-multisite.csv
      --output data/joined.csv
    deps:
      - data/2022-isb-multisite.csv
      - data/2022-clb-multisite.csv
    outs:
      - data/joined.csv

  enhance:
    desc:
      This stage fixes the super- and sub-level reporting for the LNLs and also creates
      new 'modalities' from combining existing ones, e.g. using the logical AND or
      estimating the most likely involvement based on the observations only.
    vars:
      - input: data/joined.csv
      - output: data/enhanced.csv
    cmd: >
      lyscripts data enhance ${input} ${output} ${data_cleaning_modalities}
    deps:
      - ${input}
    params:
      - modalities
    outs:
      - ${output}

  statistics:
    desc: Plot some interesting cohort statistics regarding involvement patterns.
    vars:
      - input: data/enhanced.csv
      - script: scripts/statistics.py
      - output: figures/statistics.png
    cmd: >
      .venv/bin/python ${script}
    deps:
      - ${input}
      - ${script}
    outs:
      - ${output}

  contra-involvement-table:
    desc: |
      Create table showing contralateral involvement by LNL stratified by the variables
      T-Category, midline extension, and ipsilateral involvement.
    vars:
      - input: data/enhanced.csv
      - script: scripts/contra_involvement.py
      - output: tables/contra_involvement.csv
    cmd: >
      .venv/bin/python ${script}
    deps:
      - ${input}
      - ${script}
    outs:
      - ${output}

  copy:
    desc:
      Copy the plots and tables over into the teams folder. The teams folder must be
      defined in an environment variable named `OUTPUT_DIR`.
    cmd: >
      bash copy.sh
    deps:
      - figures
      - tables
      - copy.sh
