vars:
- params.yaml


stages:
  join:
    desc: Concatenate the two datasets into one
    cmd: >
      lyscripts data join
      --inputs data/2023-isb-multisite.csv data/2023-clb-multisite.csv
      --output data/joined.csv
    deps:
      - data/2023-isb-multisite.csv
      - data/2023-clb-multisite.csv
    outs:
      - data/joined.csv

  enhance:
    desc:
      This stage fixes the super- and sub-level reporting for the LNLs and also creates
      new 'modalities' from combining existing ones, e.g. using the logical AND or
      estimating the most likely involvement based on the observations only.
    cmd: >
      lyscripts data enhance data/joined.csv data/enhanced.csv ${data_cleaning_modalities}
    deps:
      - data/joined.csv
    params:
      - modalities
    outs:
      - data/enhanced.csv

  figures:
    foreach:
      - multi_panel_statistics
      - venn_and_stacked_ece
      - dissected_vs_positive
      - contra_by_subsite
    do:
      deps:
        - scripts/shared.py
        - data/enhanced.csv
        - scripts/${item}.py
      cmd: >
        python scripts/${item}.py
      outs:
        - figures/${item}.png

  tables:
    foreach:
      - contra_involvement
      - prevalence_stratified
      - involvement_combinations
    do:
      deps:
        - scripts/shared.py
        - data/enhanced.csv
        - scripts/${item}.py
      cmd: >
        python scripts/${item}.py
      outs:
        - tables/${item}.csv

  copy:
    desc:
      Copy the plots and tables over into the teams folder. The teams folder must be
      defined in an environment variable named `OUTPUT_DIR`.
    cmd: >
      bash copy.sh
    deps:
      - figures
      - tables
      - copy.sh
