vars:
- params.yaml


stages:
  join:
    desc: Concatenate the two datasets into one
    cmd: >
      lyscripts data join
      --inputs data/2022-isb-multisite.csv data/2022-clb-multisite.csv
      --output data/joined.csv
    deps:
      - data/2022-isb-multisite.csv
      - data/2022-clb-multisite.csv
    outs:
      - data/joined.csv

  enhance:
    desc:
      This stage fixes the super- and sub-level reporting for the LNLs and also creates
      new 'modalities' from combining existing ones, e.g. using the logical AND or
      estimating the most likely involvement based on the observations only.
    vars:
      - input: data/joined.csv
      - output: data/enhanced.csv
    cmd: >
      lyscripts data enhance ${input} ${output} ${data_cleaning_modalities}
    deps:
      - ${input}
    params:
      - modalities
    outs:
      - ${output}

  figures:
    foreach:
      - statistics
      - venn_diagram
    do:
      deps:
        - data/enhanced.csv
        - scripts/${item}.py
      cmd: >
        .venv/bin/python scripts/${item}.py
      outs:
        - figures/${item}.png

  tables:
    foreach:
      - contra_involvement
      - ece_data
    do:
      deps:
        - data/enhanced.csv
        - scripts/${item}.py
      cmd: >
        .venv/bin/python scripts/${item}.py
      outs:
        - tables/${item}.csv

  copy:
    desc:
      Copy the plots and tables over into the teams folder. The teams folder must be
      defined in an environment variable named `OUTPUT_DIR`.
    cmd: >
      bash copy.sh
    deps:
      - figures
      - tables
      - copy.sh
